# TIMEOUTS
HEARTBEAT_INTERVAL = 3
RCV_TIMEOUT = 1000

# ROLES
FOLLOWER = "FOLLOWER"
CANDIDATE = "CANDIDATE"
LEADER = "LEADER"

# MESSAGE TYPES
REQUEST_VOTE = "REQUEST VOTE"
REQUEST_VOTE_RESPONSE = "REQUEST VOTE RESPONSE"
APPEND_ENTRIES_REQUEST = "APPEND ENTRIES REQUEST"
APPEND_ENTRIES_RESPONSE = "APPEND ENTRIES RESPONSE"

# MESSAGE ARGUMENTS
TYPE = "type"
TERM = "term"
CANDIDATE_ID = "candidate_id"
LAST_LOG_INDEX = "last_log_index"
LAST_LOG_TERM = "last_log_term"
VOTE_GRANTED = "vote_granted"

# OTHER
INDEX = "index"
VOTE_GRANTED = "vote_granted"