REQUEST_VOTE = "REQUEST VOTE"
REQUEST_VOTE_RESPONSE = "REQUEST VOTE RESPONSE"
FOLLOWER = "FOLLOWER"
CANDIDATE = "CANDIDATE"
LEADER = "LEADER"
APPEND_ENTRIES_REQUEST = "APPEND ENTRIES REQUEST"
APPEND_ENTRIES_RESPONSE = "APPEND ENTRIES RESPONSE"
HEARTBEAT_INTERVAL = 3
